services:
  server:
    container_name: python-server
    build:
      # Server Dockefile emplacement
      context: ./backend
      target: development
    volumes:
      # bind mount enabling modifications on the host
      - .:/project
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG:-False}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password

  client:
    container_name: react-client
    build:
      # Frontend Dockefile emplacement
      context: ./frontend
      target: development
    volumes:
      # bind mount enabling modifications on the host 
      # (app is not the same as for the server) since it is a different container
      - ./frontend:/app
      - /app/node_modules # to save in container modifications
    ports:
      - "5173:5173"
    environment:
      # to refresh when modified
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server 

  db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      # db-data is on the host but managed by docker
      # /var/lib/postgresql allows the volume to persist
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  node_modules: