services:
  server:
    container_name: python-server
    build:
      # Server Dockefile emplacement
      context: ./backend
    volumes:
      # bind mount enabling modifications on the host
      - .:/project
      # - ./frontend/src:/project/frontend	
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password

  client:
    container_name: react-client
    build:
      # Frontend Dockefile emplacement
      context: ./frontend
    volumes:
      # bind mount enabling modifications on the host (app is not the same as for the server)
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      # to refresh when modified
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server 

  db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      # db-data is on the host but managed by docker
      # /var/lib/postgresql allows the volume to persist
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  node_modules:

# Useful for production (in dev, the global .env is used)
secrets:
  db-password:
    file: "secrets/db_password.txt"